// Radiation levels
#define RADIATION_LEVEL_MAX 500
#define RADIATION_LEVEL_HIGH 400
#define RADIATION_LEVEL_MEDIUM 300
#define RADIATION_LEVEL_NORMAL 200
#define RADIATION_LEVEL_SAFE 100
#define RADIATION_LEVEL_DANGER 50
